package is.hi.hbv501g.hbv501g.Persistance.Entities;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/******************************************************************************
 *  Name    : Group 7
 *  E-mail  : sns25@hi.is, kjg18@hi.is, hrj53@hi.is, mmo15@hi.is
 *
 *  Description  : A class that generates the Exercise entity. An ID is
 *  autogenerated for each exercise. There is a OneToMany connection from the
 *  Exercise entity to the ExerciseCombo entity.
 *****************************************************************************/

@Entity
@Table(name = "exercises")
public class Exercise {
    @Id
    private String title;
    private String bodyPart;
    private String type;
    @OneToMany(mappedBy = "exercise",cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ExerciseCombo> exerciseCombo = new ArrayList<>();

    public Exercise() {
    }

    public Exercise(String title, String bodyPart, String type) {
        this.title = title;
        this.bodyPart = bodyPart;
        this.type = type;
    }

    public String getType() {
        return type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
