package is.hi.hbv501g.hbv501g.Persistance.Entities;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/******************************************************************************
 *  Name    : Group 7
 *  E-mail  : sns25@hi.is, kjg18@hi.is, hrj53@hi.is, mmo15@hi.is
 *
 *  Description  : A class that generates the Workout entity. An ID is
 *  autogenerated for each workout. There is a OneToMany connection from
 *  the Workout entity to the ExerciseCombo entity and a ManyToMany connection
 *  from the Workout entity to the User entity.
 *****************************************************************************/

@Entity
@Table(name= "workouts")
public class Workout {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long ID;
    private String title;
    private int duration;
    private String description;
    @OneToMany(mappedBy = "workout",cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ExerciseCombo> exerciseCombo = new ArrayList<>();

    @ManyToMany(fetch = FetchType.EAGER)
    private List<User> user = new ArrayList<>();

    private boolean madeByAdmin;

    public Workout() {
    }

    public boolean isMadeByAdmin() {
        return madeByAdmin;
    }

    public Workout(String title, int duration, String description) {
        this.title = title;
        this.duration = duration;
        this.description = description;
        this.madeByAdmin = false;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    public void setUser(List<User> user) {
        this.user = user;
    }

    public String getDescription() {return description;}
    public List<ExerciseCombo> getExerciseCombo() {
        return exerciseCombo;
    }
    public List<User> getUser() {
        return  user;
    }
    public void setExerciseCombo(List<ExerciseCombo> exerciseCombo) {
        this.exerciseCombo = exerciseCombo;
    }
}



